sonar.projectKey=Adyen_adyen-shopware6
sonar.organization=adyen

# Shopware plugins do not commit composer.lock
# Suppress the "missing lock file" rule on composer.json.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=text:S8567
sonar.issue.ignore.multicriteria.e1.resourceKey=**/composer.json