version: '3'

services:
  playwright:
    image: mcr.microsoft.com/playwright:focal
    shm_size: 1gb
    ipc: host
    cap_add:
      - SYS_ADMIN
    environment:
      - INTEGRATION_TESTS_BRANCH
      - SHOPWARE_BASE_URL
    command: chmod +x /e2e.sh
    volumes:
      - ../scripts/e2e.sh:/e2e.sh
      - ../../../test-report:/tmp/test-report
