version: '3'

services:
  playwright:
    image: mcr.microsoft.com/playwright:focal
    networks:
      - localnetwork
    shm_size: 1gb
    ipc: host
    cap_add:
      - SYS_ADMIN
    environment:
      - INTEGRATION_TESTS_BRANCH
      - SHOPWARE_BASE_URL
    volumes:
      - type: bind
        source: ../scripts
        target: /tmp/scripts
      - type: volume
        source: ../../test-report
        target: /tmp/test-report
        volume:
          nocopy: true

volumes:
  ../../test-report:
