name: Testing Workflow

on: ["push", "pull_request"]

jobs:
  e2e:
    name: Plugin v${{ matrix.plugin }} | Shopware
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    #      matrix:
    #        plugin: ['1.2']
    steps:

      - name: Clone Code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v1.2

      - name: Download Docker
        run: |
          docker pull dockware/dev:latest

      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/adyen-shopware6
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/adyen-shopware6
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

      - name: Install and Build Artifacts
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/adyen-shopware6 && make install -B'
#          docker exec shop bash -c 'cd /var/www/html/custom/plugins/adyen-shopware6 && make build -B'

      - name: Install/Configure Plugin
        run: |
               docker exec shop bash -c 'php bin/console plugin:refresh'
               docker exec shop bash -c 'php bin/console plugin:install adyen-shopware6 --activate'
#                    docker exec shop bash -c 'php bin/console system:config:set adyen-shopware6.config.MyKey ${{ secrets.MYKEY_TEST }}'
               docker exec shop bash -c 'php bin/console cache:clear'