name: Testing Workflow

on: ["push", "pull_request"]

jobs:
  e2e:
    name: Plugin v${{ matrix.plugin }} | Shopware
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Download Dockware
        run: |
          docker pull dockware/dev:latest

      - name: Start Dockware
        run: |
          docker run --rm -p 80:80 -p 443:443 --name shopware6 --env PHP_VERSION=7.4 -d dockware/dev:latest
          sleep 30
          docker logs shop
#          # now change the domain of our shop if required
#          sudo echo "127.0.0.1 local.shopware.shop" | sudo tee -a /etc/hosts
#          docker exec shop bash -c "mysql -u root -proot shopware -e \"UPDATE sales_channel_domain SET url='https://local.shopware.shop' WHERE url NOT LIKE 'default.%';\""

      - name: Install Adyen Plugin
        run: |
          docker exec shopware6 bash -c 'composer require adyen/adyen-shopware6'
#          docker cp $(pwd)/. shopware6:/var/www/html/custom/plugins/adyen-shopware6
#          docker exec shopware6 bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
#
#      - name: Upload into Docker
#        run: |
#          docker cp $(pwd)/. shopware6:/var/www/html/custom/plugins/adyen-shopware6
#          docker exec shopware6 bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
#
#      - name: Install and Build Artifacts
#        run: |
#          docker exec shop bash -c 'cd /var/www/html/custom/plugins/adyen-shopware6 && make install -B'
#          docker exec shop bash -c 'cd /var/www/html/custom/plugins/adyen-shopware6 && make build -B'

      - name: Install/Configure Plugin
        run: |
          docker exec shopware6 bash -c 'php bin/console plugin:refresh'
          docker exec shopware6 bash -c 'php bin/console plugin:install AdyenPaymentShopware6 --activate'
          docker exec shopware6 bash -c 'php bin/console cache:clear'
