#on: ["push", "pull_request"]
name: Shopware Marketplace Artifact

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare release artifact
        run: .github/workflows/scripts/prepare-release.sh

      - name: Marketplace Release Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AdyenPaymentShopware6
          path: AdyenPaymentShopware6.zip
