on: ["push", "pull_request"]
name: Shopware Marketplace Artifact

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare release artifact
        run: .github/workflows/scripts/prepare-release.sh

      - name: Update current directory
        run: cd ..

      - name: Marketplace Release Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: marketplace-release-zip
          path: AdyenPaymentShopware6.zip

#      - name: Test with E2E
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-e2e-upload
#          path: .github/workflows/scripts/e2e.sh