on: ["push", "pull_request"]
name: Shopware Marketplace Artifact

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare release artifact
        run: scripts/prepare-release.sh

      - name: Marketplace Release Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: marketplace-release-zip
          path: scripts/AdyenPaymentShopware6.zip